### ISSUE TITLE
Some TODO's for Iteration 2

### ISSUE THREAD

**Issue by pdatascience** [pensoft/OpenBiodiv#15]
- [x] add rule to match authors with affiliation string (not only institution ID) 
- [x] figure out why processing of BDJ stopped 
- [ ] expand to all Pensoft journals 
- [ ] expand to Plazi 
- [x] improve logger with eventType and eventDate
- [x] zookeys email
- [x] matching of keywords - lookup problem -> look at the lookup problems below
- [x] NS troubleshooting when you load both fabio and foaf
- [x] comas, such as in University of California, berkeley
- [ ] matching statistics from the log 
- [ ] SPARQL authors that have been multiple papers
- [ ] SPARQL authors that have the same name, but different ID's
- [ ] SPARQL specific authors such as Lyubomir Penev
- [ ] SPARQL authors that are not members of any organization or have no emails or both

**Comment by pdatascience** [comment]
for the lookup, but they are linked with OWL:sameAs return a random of the two

**Comment by ramorrismorris** [comment]
Not sure if this is the place to call attention to the frequently cited paper by Halpin et. al "[When owl:sameAs Isn’t the Same: An Analysis of Identity in Linked Data](https://link.springer.com/chapter/10.1007/978-3-642-17746-0_20)"

**Comment by pdatascience** [comment]
I am well aware of this paper, but the issue is here somewhat different. At the moment, as I'm mostly done with the ontology I am generating the Linked Open Data dataset with the help of R scripts in this repository. Among others I have a function that looks up a URI given the label of the resource, `lookup_id`. This is a reminder to myself to make the function robust in such a way that should there be a `owl:sameAs` between two URI's, then then function should return only one of them.

More generally speaking I do need to use `owl:sameAs` in certain scenarios where the resources are trully the same resource, as in the same person for example. One possible scenario would be where I disamgiguate person URI's with the help of Pensoft's relational database.

We will do two passes: first, process the XML's, create URI's for different people, try to disambiguate based on the information found in the XML. Second, ask the relational database to provide additional details about the people (such as emails etc,). Based on this new information, potentially merge nodes.

**Comment by ramorrismorris** [comment]
Your goal is clear and worthy, but if I understand what you think you might do, it seems you would also depend on adding logic based on XML and DBMS semantics.  If a third party wants to use your proposed owl ontology to model an LOD data object, and if it hopes to participate in the above mentioned certain scenarios, it seems it would be required also to provide the non-rdf semantics.

**Comment by pdatascience** [comment]
I am in the process of writing a paper about this ontology in the Journal of Biomedical Semantics, so yes, I will publish all of the semantics I use. I am not quite sure if I rely on external semantics. What I do is I merge several data-sources into OBKMS and I use the ontology described here for this purpose. The user of the system is only working with the LOD that has been generated through this process. As I cannot guarantee, that I will be able to merge all identifiers at the point of generating the dataset, I do allow `owl:sameAs`.
